server:
  port: 8888
spring:
  application:
    namme: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LUNG18/spring-cloud
          searchPaths: helloworldConfig
management:
  endpoints:
    web:
      exposure:
        include: '*'
